---
title: "Who are we?"
---

The CBCS Coding Club comprises a group of students and early career researchers in CBCS and SENV at the University of Queensland. Coding Club is currently co-led by:

## Liana van Woesik

::::: columns
::: {.column width="40%" align="center"}
<a href="mailto:l.vanwoesik@student.uq.edu.au" target="_blank" class="icons">{{< iconify mdi-light:email >}}</a>
:::

::: {.column width="60%"}
Liana is a PhD student working on the Moreton Bay region of Queensland, Australia where she focuses on data analysis of water-quality, land–sea conservation planning and management, marine science, and pollution impacts on coastal ecosystems. Liana loves coding in R for its powerful statistics, amazing data-visualization tools, and huge ecosystem of packages that facilitate impactful science.

{{< iconify catppuccin:r size=50px >}} {{< iconify catppuccin:powershell size=50px >}} {{< iconify catppuccin:database size=50px >}}
:::
:::::

## Angela Liu

::::: columns
::: {.column width="40%" align="center"}
<a href="mailto:angela.liu2@uq.edu.au" target="_blank" class="icons">{{< iconify mdi-light:email >}}</a>
:::

::: {.column width="60%"}
Angela is a PhD student studying the migratory connectivity of marine megavertebrates, and how policy and spatial planning can better integrate these species. Angela primarily works in R, and she is interested in movement modelling, network analysis, and spatial prioritization.

{{< iconify catppuccin:r size=50px >}} {{< iconify catppuccin:powershell size=50px >}} {{< iconify catppuccin:database size=50px >}}
:::
:::::

## Ben Lucas

::::: columns
::: {.column width="40%" align="center"}
<a href="https://scholar.google.com/citations?user=ENgDFQcAAAAJ&hl=en" target="_blank" class="icons">{{< iconify academicons:google-scholar >}}</a> <a href="https://www.linkedin.com/in/benalucas/" target="_blank" class="icons">{{< iconify mdi:linkedin >}}</a> <a href="mailto:b.lucas@uq.edu.au" target="_blank" class="icons">{{< iconify mdi-light:email >}}</a>
:::

::: {.column width="60%"}
Ben is an ecological connectivity researcher, looking into enhancing connectivity implementation under the global biodiversity framework via clarifying conceptual gaps and comparing methods of connectivity measurement. Ben works with R, Julia, NetLogo, and Bash, but also has interest in Python and statistical inference approaches. 

{{< iconify catppuccin:r size=50px >}} {{< iconify catppuccin:powershell size=50px >}} {{< iconify catppuccin:database size=50px >}} {{< iconify catppuccin:julia size=50px >}}
:::
:::::

# Past co-leads

::::: columns
::: {.column width="50%"}
### Caitie Kuempel

<a href="https://scholar.google.com/citations?user=nE8IeT4AAAAJ&hl=en&oi=ao" target="_blank" class="icons">{{< iconify academicons:google-scholar >}}</a> <a href="https://www.linkedin.com/in/caitie-kuempel-b86905110/" target="_blank" class="icons">{{< iconify mdi:linkedin >}}</a>

### Kristine (Tin) Buenafe

<a href="https://snbuenafe.github.io" target="_blank" class="icons">{{< iconify streamline:web >}}</a> <a href="https://scholar.google.com/citations?user=jEIS64UAAAAJ&hl=en&oi=ao" target="_blank" class="icons">{{< iconify academicons:google-scholar >}}</a> <a href="www.linkedin.com/in/tin-buenafe" target="_blank" class="icons">{{< iconify mdi:linkedin >}}</a> <a href="mailto:k.buenafe@uq.edu.au" target="_blank" class="icons">{{< iconify mdi-light:email >}}</a>

### Fei Chung
<a href="https://scholar.google.com/citations?hl=en&user=DRhjtzwAAAAJ" target="_blank" class="icons">{{< iconify academicons:google-scholar >}}</a> <a href="https://www.linkedin.com/in/chungyifei/" target="_blank" class="icons">{{< iconify mdi:linkedin >}}</a> <a href="mailto:yifei.chung@uq.edu.au" target="_blank" class="icons">{{< iconify mdi-light:email >}}</a>

### Rosa Mar Dominguez-Martinez
<a href="https://scholar.google.com/citations?hl=en&user=mUWn6W0AAAAJ" target="_blank" class="icons">{{< iconify academicons:google-scholar >}}</a> <a href="https://www.linkedin.com/in/rosa-mar-dominguez-martinez-427a5014a/" target="_blank" class="icons">{{< iconify mdi:linkedin >}}</a> <a href="mailto:r.dominguezmartinez@uq.edu.au" target="_blank" class="icons">{{< iconify mdi-light:email >}}</a>

:::

::: {.column width="50%"}
:::
:::::
